In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
from IPython.core.display import display, HTML
from IPython.display import clear_output
display(HTML("<style>.container { width:90% }</style>"))

C:\Users\rli4\AppData\Local\Temp\ipykernel_41588\2466406673.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

## Step 1: pip install required packages if not installed already

In [3]:
# !pip install autogluon
import benchmark_ag
from benchmark_ag import load_data, run_ag

## Step 2: download data using fdb
Example: https://github.com/amazon-research/fraud-dataset-benchmark/blob/main/scripts/examples/Test_FDB_Loader.ipynb

In [4]:
# This is where datasets are stored: {BASE_PATH}/{dataset}/
BASE_PATH = r"C:\Users\rli4\OneDrive - FTI Consulting\Documents\GitHub3\fraud-dataset-benchmark\scripts\examples"
dataset = "fakejob"

Make sure three files are downloaded:
1. {BASE_PATH}/{dataset}/train.csv
2. {BASE_PATH}/{dataset}/test.csv
3. {BASE_PATH}/{dataset}/test_labels.csv

## Step 3: look at data

In [5]:
features, df_train, df_test = load_data(dataset, BASE_PATH)

INFO: benchmark_utils.py: fakejob
INFO: benchmark_utils.py: (14304, 18)
INFO: benchmark_utils.py: (3576, 17)
INFO: benchmark_utils.py: (3576, 2)
INFO: benchmark_utils.py: (3576, 18)
INFO: benchmark_utils.py: 16
INFO: benchmark_utils.py: ['title', 'location', 'department', 'salary_range', 'company_profile', 'description', 'requirements', 'benefits', 'telecommuting', 'has_company_logo', 'has_questions', 'employment_type', 'required_experience', 'required_education', 'industry', 'function']

In [13]:
df_train.shape

(14304, 18)

In [6]:
df_train.head()

,EVENT_ID,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,EVENT_LABEL
0,5737,Jr. Business Analyst & Quality Analyst (entry...,"US, NJ, PISCATAWAY",NaN,NaN,NaN,"Duration: Full time / W2Location: Piscataway,N...",What we require:-- Masters degree in Computers...,NaN,0,0,0,Full-time,Entry level,Master's Degree,Financial Services,Finance,0
1,7107,English Teacher Abroad,"US, PA, Scranton",NaN,NaN,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,0,1,1,Contract,NaN,Bachelor's Degree,Education Management,NaN,0
2,11979,SQL Server Database Developer Job opportunity ...,"US, IL, Barrington",NaN,90000-100000,We are an innovative personnel-sourcing firm w...,Position : SQL Server Database DeveloperJob Lo...,Position : SQL Server Database DeveloperJob Lo...,Benefits - FullBonus Eligible - Yes,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,0
3,9375,Legal Analyst - 12 Month FTC,"GB, LND, London",Legal,NaN,MarketInvoice is one of the most high-profile ...,DescriptionOur mission at MarketInvoice is to ...,Duties and ResponsibilitiesReviewing contractu...,Competitive salaryPrivate HealthcareHalf price...,0,1,0,Full-time,Associate,Professional,Financial Services,Legal,0
4,1301,Part-Time Finance Assistant,"GB, LND,",NaN,NaN,NaN,Salary:£9 - £10 per hour We are currently goin...,"Your role will be a varied, interesting and in...",Salary:£9 - £10 per hour,0,0,0,Part-time,NaN,NaN,Accounting,NaN,0

In [14]:
df_train.isna().sum()

EVENT_ID                   0
title                      0
location                 281
department              9273
salary_range           12012
company_profile         2621
description                1
requirements            2185
benefits                5772
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         2748
required_experience     5638
required_education      6505
industry                3898
function                5154
EVENT_LABEL                0
dtype: int64

In [7]:
df_test.head()

,EVENT_ID,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,EVENT_LABEL
0,10,Customer Service Associate - Part Time,"US, AZ, Phoenix",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...",The Customer Service Associate will be based i...,Minimum Requirements:Minimum of 6 months custo...,NaN,0,1,0,Part-time,Entry level,High School or equivalent,Financial Services,Customer Service,0
1,15,Account Executive - Sydney,"AU, NSW, Sydney",Sales,NaN,Adthena is the UK’s leading competitive intell...,Are you interested in a satisfying and financi...,You’ll need to be smart and passionate and hav...,"In return we'll pay you well, give you some ow...",0,1,0,Full-time,Associate,Bachelor's Degree,Internet,Sales,0
2,16,VP of Sales - Vault Dragon,"SG, 01, Singapore",Sales,120000-150000,Jungle Ventures is the leading Singapore based...,About Vault Dragon Vault Dragon is Dropbox for...,Key Superpowers3-5 years of high-pressure sale...,"Basic: SGD 120,000Equity negotiable for a rock...",0,1,1,Full-time,Executive,Bachelor's Degree,Facilities Services,Sales,0
3,19,Visual Designer,"US, NY, New York",NaN,NaN,Kettle is an independent digital agency based ...,Kettle is hiring a Visual Designer!Job Locatio...,NaN,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
4,21,Marketing Assistant,"US, TX, Austin",NaN,NaN,IntelliBright was created to leverage enterpri...,IntelliBright is growing fast and is looking f...,Job RequirementsAssist in creating client onli...,NaN,0,1,0,NaN,NaN,NaN,NaN,Marketing,0

## Step 3: run Autogluon

1. The function run_ag below also saves a leaderboard file (leaderboard_xxx.csv) and a test metrics file (test_metrics_xxx.joblib) into {BASE_PATH}/{dataset}/, respectively
2. AutoGluon models are saved at {BASE_PATH}/{dataset}/AutogluonModels

In [22]:
run_ag(dataset, BASE_PATH, time_limit=3600, presets='best_quality')

INFO: benchmark_utils.py: fakejob
INFO: benchmark_utils.py: (14304, 18)
INFO: benchmark_utils.py: (3576, 17)
INFO: benchmark_utils.py: (3576, 2)
INFO: benchmark_utils.py: (3576, 18)
INFO: benchmark_utils.py: 16
INFO: benchmark_utils.py: ['title', 'location', 'department', 'salary_range', 'company_profile', 'description', 'requirements', 'benefits', 'telecommuting', 'has_company_logo', 'has_questions', 'employment_type', 'required_experience', 'required_education', 'industry', 'function']
Presets specified: ['best_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Dynamic stacking is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
Detecting stacked overfitting by sub-fitting AutoGluon on the input data. That is, copies of AutoGluon will be sub-fit on subset(s) of the data. Then, the holdout validation data is used to detect stacked overfitting.
Sub-fit(s) time limit is: 3600 seconds.
Starting holdout-based sub-fit for dynamic stacking. Context path is: C:\Users\rli4\OneDrive - FTI Consulting\Documents\GitHub3\fraud-dataset-benchmark\scripts\examples/fakejob/AutogluonModels/ag-20240807_131441_best_quality//ds_sub_fit/sub_fit_ho.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "C:\Users\rli4\OneDrive - FTI Consulting\Documents\GitHub3\fraud-dataset-benchmark\scripts\examples/fakejob/AutogluonModels/ag-20240807_131441_best_quality//ds_sub_fit/sub_fit_ho"
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.10.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.19045
CPU Count:          20
Memory Avail:       39.97 GB / 63.66 GB (62.8%)
Disk Space Avail:   723.27 GB / 951.65 GB (76.0%)
===================================================
Train Data Rows:    12714
Train Data Columns: 16
Label Column:       EVENT_LABEL
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    40973.43 MB
	Train Data (Original)  Memory Usage: 59.75 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['title', 'location', 'company_profile', 'description', 'requirements', 'benefits']
			CountVectorizer fit with vocabulary size = 10000
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])          : 3 | ['telecommuting', 'has_company_logo', 'has_questions']
		('object', [])       : 7 | ['department', 'salary_range', 'employment_type', 'required_experience', 'required_education', ...]
		('object', ['text']) : 6 | ['title', 'location', 'company_profile', 'description', 'requirements', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :    7 | ['department', 'salary_range', 'employment_type', 'required_experience', 'required_education', ...]
		('category', ['text_as_category'])  :    6 | ['title', 'location', 'company_profile', 'description', 'requirements', ...]
		('int', ['binned', 'text_special']) :  152 | ['title.char_count', 'title.word_count', 'title.capital_ratio', 'title.lower_ratio', 'title.digit_ratio', ...]
		('int', ['bool'])                   :    3 | ['telecommuting', 'has_company_logo', 'has_questions']
		('int', ['text_ngram'])             : 8911 | ['__nlp__.00', '__nlp__.000', '__nlp__.0pt', '__nlp__.10', '__nlp__.10 years', ...]
	118.9s = Fit runtime
	16 features in original data used to generate 9079 features in processed data.
	Train Data (Processed) Memory Usage: 218.23 MB (0.5% of available memory)
Data preprocessing and feature engineering runtime = 121.52s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 518.85s of the 777.55s of remaining time.
	0.8911	 = Validation score   (roc_auc)
	8.74s	 = Training   runtime
	76.85s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 411.5s of the 670.62s of remaining time.
	0.8955	 = Validation score   (roc_auc)
	8.8s	 = Training   runtime
	81.97s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 306.54s of the 565.58s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.59%)
	0.9931	 = Validation score   (roc_auc)
	220.27s	 = Training   runtime
	18.6s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 174.41s of remaining time.
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.99, 'KNeighborsDist_BAG_L1': 0.01}
	0.9932	 = Validation score   (roc_auc)
	1.76s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 11 L2 models ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 172.44s of the 164.25s of remaining time.
	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 10.10% memory usage per fold, 40.42%/80.00% total).
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=5, gpus=0, memory=10.10%)
	0.9915	 = Validation score   (roc_auc)
	262.28s	 = Training   runtime
	10.53s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the -274.57s of remaining time.
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.818, 'LightGBMXT_BAG_L2': 0.182}
	0.9935	 = Validation score   (roc_auc)
	1.95s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1177.55s ... Best model: "WeightedEnsemble_L3"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("C:\Users\rli4\OneDrive - FTI Consulting\Documents\GitHub3\fraud-dataset-benchmark\scripts\examples/fakejob/AutogluonModels/ag-20240807_131441_best_quality//ds_sub_fit/sub_fit_ho")
Leaderboard on holdout data from dynamic stacking:
                   model  holdout_score  score_val eval_metric  pred_time_test  pred_time_val  fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      LightGBMXT_BAG_L2          0.991      0.991     roc_auc          57.222        187.953   500.085                    4.692                  10.526            262.276            2       True          5
1    WeightedEnsemble_L2          0.991      0.993     roc_auc          27.650        100.579   230.827                    0.010                   0.004              1.762            2       True          4
2    WeightedEnsemble_L3          0.991      0.993     roc_auc          57.233        187.953   502.034                    0.011                   0.000              1.949            3       True          6
3      LightGBMXT_BAG_L1          0.990      0.993     roc_auc           5.365         18.602   220.267                    5.365                  18.602            220.267            1       True          3
4  KNeighborsDist_BAG_L1          0.893      0.896     roc_auc          22.274         81.973     8.799                   22.274                  81.973              8.799            1       True          2
5  KNeighborsUnif_BAG_L1          0.888      0.891     roc_auc          24.891         76.852     8.743                   24.891                  76.852              8.743            1       True          1
Stacked overfitting occurred: True.
Spend 1245 seconds for the sub-fit(s) during dynamic stacking.
Time left for full fit of AutoGluon: 2355 seconds.
Starting full fit now with num_stack_levels 0.
Beginning AutoGluon training ... Time limit = 2355s
AutoGluon will save models to "C:\Users\rli4\OneDrive - FTI Consulting\Documents\GitHub3\fraud-dataset-benchmark\scripts\examples/fakejob/AutogluonModels/ag-20240807_131441_best_quality/"
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.10.13
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.19045
CPU Count:          20
Memory Avail:       24.39 GB / 63.66 GB (38.3%)
Disk Space Avail:   723.08 GB / 951.65 GB (76.0%)
===================================================
Train Data Rows:    14304
Train Data Columns: 16
Label Column:       EVENT_LABEL
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    25051.67 MB
	Train Data (Original)  Memory Usage: 92.32 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['title', 'location', 'company_profile', 'description', 'requirements', 'benefits']
			CountVectorizer fit with vocabulary size = 10000
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])          : 3 | ['telecommuting', 'has_company_logo', 'has_questions']
		('object', [])       : 7 | ['department', 'salary_range', 'employment_type', 'required_experience', 'required_education', ...]
		('object', ['text']) : 6 | ['title', 'location', 'company_profile', 'description', 'requirements', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :    7 | ['department', 'salary_range', 'employment_type', 'required_experience', 'required_education', ...]
		('category', ['text_as_category'])  :    6 | ['title', 'location', 'company_profile', 'description', 'requirements', ...]
		('int', ['binned', 'text_special']) :  152 | ['title.char_count', 'title.word_count', 'title.capital_ratio', 'title.lower_ratio', 'title.digit_ratio', ...]
		('int', ['bool'])                   :    3 | ['telecommuting', 'has_company_logo', 'has_questions']
		('int', ['text_ngram'])             : 8873 | ['__nlp__.00', '__nlp__.000', '__nlp__.0in', '__nlp__.0in 4pt', '__nlp__.0pt', ...]
	168.7s = Fit runtime
	16 features in original data used to generate 9041 features in processed data.
	Train Data (Processed) Memory Usage: 244.49 MB (1.3% of available memory)
Data preprocessing and feature engineering runtime = 173.92s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 2181.07s of the 2179.67s of remaining time.
	0.8877	 = Validation score   (roc_auc)
	16.31s	 = Training   runtime
	208.9s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 1922.78s of the 1919.71s of remaining time.
	0.892	 = Validation score   (roc_auc)
	23.23s	 = Training   runtime
	251.63s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1604.11s of the 1602.82s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=8.00%)
	0.9929	 = Validation score   (roc_auc)
	257.63s	 = Training   runtime
	12.45s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1211.83s of the 1209.65s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.94%)
	0.991	 = Validation score   (roc_auc)
	287.57s	 = Training   runtime
	11.27s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 847.9s of the 845.17s of remaining time.
	0.9924	 = Validation score   (roc_auc)
	41.79s	 = Training   runtime
	287.21s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 497.95s of the 497.22s of remaining time.
	0.9927	 = Validation score   (roc_auc)
	30.49s	 = Training   runtime
	596.88s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the -189.87s of remaining time.
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.358, 'LightGBM_BAG_L1': 0.269, 'RandomForestEntr_BAG_L1': 0.239, 'RandomForestGini_BAG_L1': 0.119, 'KNeighborsDist_BAG_L1': 0.015}
	0.9942	 = Validation score   (roc_auc)
	8.08s	 = Training   runtime
	0.01s	 = Validation runtime
AutoGluon training complete, total runtime = 2555.4s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("C:\Users\rli4\OneDrive - FTI Consulting\Documents\GitHub3\fraud-dataset-benchmark\scripts\examples/fakejob/AutogluonModels/ag-20240807_131441_best_quality/")
INFO: benchmark_ag.py: auc on test data: 0.9968851726961875
INFO: benchmark_ag.py: tpr@1%fpr on test data: 0.9358288770053476

In [8]:
from autogluon.tabular import TabularPredictor

predictor = TabularPredictor.load(r"C:\Users\rli4\OneDrive - FTI Consulting\Documents\GitHub3\fraud-dataset-benchmark\scripts\examples/fakejob/AutogluonModels/ag-20240807_131441_best_quality/")

In [15]:
predictor.fit_summary()

*** Summary of fit() ***
Estimated performance of each model:
                     model  score_val eval_metric  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      WeightedEnsemble_L2      0.994     roc_auc       1159.444   648.788                   0.008              8.083            2       True          7
1        LightGBMXT_BAG_L1      0.993     roc_auc         12.454   257.628                  12.454            257.628            1       True          3
2  RandomForestEntr_BAG_L1      0.993     roc_auc        596.876    30.492                 596.876             30.492            1       True          6
3  RandomForestGini_BAG_L1      0.992     roc_auc        287.209    41.792                 287.209             41.792            1       True          5
4          LightGBM_BAG_L1      0.991     roc_auc         11.266   287.565                  11.266            287.565            1       True          4
5    KNeighborsDist_BAG_L1      0.892     roc_auc        251.631    23.229                 251.631             23.229            1       True          2
6    KNeighborsUnif_BAG_L1      0.888     roc_auc        208.899    16.310                 208.899             16.310            1       True          1
Number of models trained: 7
Types of models trained:
{'StackerEnsembleModel_RF', 'WeightedEnsembleModel', 'StackerEnsembleModel_KNN', 'StackerEnsembleModel_LGB'}
Bagging used: True  (with 8 folds)
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', [])                    :    7 | ['department', 'salary_range', 'employment_type', 'required_experience', 'required_education', ...]
('category', ['text_as_category'])  :    6 | ['title', 'location', 'company_profile', 'description', 'requirements', ...]
('int', ['binned', 'text_special']) :  152 | ['title.char_count', 'title.word_count', 'title.capital_ratio', 'title.lower_ratio', 'title.digit_ratio', ...]
('int', ['bool'])                   :    3 | ['telecommuting', 'has_company_logo', 'has_questions']
('int', ['text_ngram'])             : 8873 | ['__nlp__.00', '__nlp__.000', '__nlp__.0in', '__nlp__.0in 4pt', '__nlp__.0pt', ...]
*** End of fit() summary ***

c:\Users\rli4\AppData\Local\miniconda3\envs\py310\lib\site-packages\autogluon\core\utils\plots.py:169: UserWarning: AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"
  warnings.warn('AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"')

{'model_types': {'KNeighborsUnif_BAG_L1': 'StackerEnsembleModel_KNN',
  'KNeighborsDist_BAG_L1': 'StackerEnsembleModel_KNN',
  'LightGBMXT_BAG_L1': 'StackerEnsembleModel_LGB',
  'LightGBM_BAG_L1': 'StackerEnsembleModel_LGB',
  'RandomForestGini_BAG_L1': 'StackerEnsembleModel_RF',
  'RandomForestEntr_BAG_L1': 'StackerEnsembleModel_RF',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'KNeighborsUnif_BAG_L1': 0.8877022064287742,
  'KNeighborsDist_BAG_L1': 0.8919626542000514,
  'LightGBMXT_BAG_L1': 0.9929389955547149,
  'LightGBM_BAG_L1': 0.991035386631717,
  'RandomForestGini_BAG_L1': 0.9923628109335098,
  'RandomForestEntr_BAG_L1': 0.992735890610855,
  'WeightedEnsemble_L2': 0.994247882071584},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'KNeighborsUnif_BAG_L1': ['KNeighborsUnif_BAG_L1'],
  'KNeighborsDist_BAG_L1': ['KNeighborsDist_BAG_L1'],
  'LightGBMXT_BAG_L1': ['LightGBMXT_BAG_L1'],
  'LightGBM_BAG_L1': ['LightGBM_BAG_L1'],
  'RandomForestGini_BAG_L1': ['RandomForestGini_BAG_L1'],
  'RandomForestEntr_BAG_L1': ['RandomForestEntr_BAG_L1'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'KNeighborsUnif_BAG_L1': 16.310004949569702,
  'KNeighborsDist_BAG_L1': 23.22900629043579,
  'LightGBMXT_BAG_L1': 257.6279773712158,
  'LightGBM_BAG_L1': 287.56510162353516,
  'RandomForestGini_BAG_L1': 41.79171347618103,
  'RandomForestEntr_BAG_L1': 30.49152708053589,
  'WeightedEnsemble_L2': 8.082793474197388},
 'model_pred_times': {'KNeighborsUnif_BAG_L1': 208.89931678771973,
  'KNeighborsDist_BAG_L1': 251.63148403167725,
  'LightGBMXT_BAG_L1': 12.453747987747192,
  'LightGBM_BAG_L1': 11.266223430633545,
  'RandomForestGini_BAG_L1': 287.20893144607544,
  'RandomForestEntr_BAG_L1': 596.8757169246674,
  'WeightedEnsemble_L2': 0.007988452911376953},
 'num_bag_folds': 8,
 'max_stack_level': 2,
 'num_classes': 2,
 'model_hyperparams': {'KNeighborsUnif_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'KNeighborsDist_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'LightGBMXT_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'LightGBM_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True},
  'RandomForestGini_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'RandomForestEntr_BAG_L1': {'use_orig_features': True,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True,
   'use_child_oof': True},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'max_base_models': 25,
   'max_base_models_per_type': 5,
   'save_bag_folds': True}},
 'leaderboard':                      model  score_val eval_metric  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
 0      WeightedEnsemble_L2      0.994     roc_auc       1159.444   648.788                   0.008              8.083            2       True          7
 1        LightGBMXT_BAG_L1      0.993     roc_auc         12.454   257.628                  12.454            257.628            1       True          3
 2  RandomForestEntr_BAG_L1      0.993     roc_auc        596.876    30.492                 596.876             30.492            1       True          6
 3  RandomForestGini_BAG_L1      0.992     roc_auc        287.209    41.792                 287.209             41.792            1       True          5
 4          LightGBM_BAG_L1      0.991     roc_auc         11.266   287.565                  11.266            287.565            1       True          4
 5    KNeighborsDist_BAG_L1      0.892     roc_auc        251.631    23.229                 251.631             23.229            1       True          2
 6    KNeighborsUnif_BAG_L1      0.888     roc_auc        208.899    16.310                 208.899             16.310            1       True          1}

In [9]:
train_data_transformed = predictor.transform_features()

In [10]:
train_data_transformed

,telecommuting,has_company_logo,has_questions,title,location,department,salary_range,company_profile,description,requirements,benefits,employment_type,required_experience,required_education,industry,function,title.char_count,title.word_count,title.capital_ratio,title.lower_ratio,title.digit_ratio,title.special_ratio,title.symbol_count.&,title.symbol_ratio.&,title.symbol_count..,title.symbol_ratio..,title.symbol_count.:,title.symbol_ratio.:,title.symbol_count.,title.symbol_ratio.,title.symbol_count./,title.symbol_ratio./,title.symbol_count.-,title.symbol_ratio.-,location.char_count,location.word_count,location.capital_ratio,location.lower_ratio,location.digit_ratio,location.special_ratio,location.symbol_count.,location.symbol_ratio.,company_profile.char_count,company_profile.word_count,company_profile.capital_ratio,company_profile.lower_ratio,company_profile.digit_ratio,company_profile.special_ratio,company_profile.symbol_count.!,company_profile.symbol_ratio.!,company_profile.symbol_count.?,company_profile.symbol_ratio.?,company_profile.symbol_count.%,company_profile.symbol_ratio.%,company_profile.symbol_count.$,company_profile.symbol_ratio.$,company_profile.symbol_count.*,company_profile.symbol_ratio.*,company_profile.symbol_count.&,company_profile.symbol_ratio.&,company_profile.symbol_count.#,company_profile.symbol_ratio.#,company_profile.symbol_count..,company_profile.symbol_ratio..,company_profile.symbol_count.:,company_profile.symbol_ratio.:,company_profile.symbol_count.,company_profile.symbol_ratio.,company_profile.symbol_count./,company_profile.symbol_ratio./,company_profile.symbol_count.;,company_profile.symbol_ratio.;,company_profile.symbol_count.-,company_profile.symbol_ratio.-,description.char_count,description.word_count,description.capital_ratio,description.lower_ratio,description.digit_ratio,description.special_ratio,description.symbol_count.!,description.symbol_ratio.!,description.symbol_count.?,description.symbol_ratio.?,description.symbol_count.%,description.symbol_ratio.%,description.symbol_count.$,description.symbol_ratio.$,description.symbol_count.*,description.symbol_ratio.*,description.symbol_count.&,description.symbol_ratio.&,description.symbol_count.#,description.symbol_ratio.#,description.symbol_count..,description.symbol_ratio..,description.symbol_count.:,description.symbol_ratio.:,description.symbol_count.,description.symbol_ratio.,description.symbol_count./,description.symbol_ratio./,description.symbol_count.;,description.symbol_ratio.;,description.symbol_count.-,description.symbol_ratio.-,requirements.char_count,requirements.word_count,requirements.capital_ratio,requirements.lower_ratio,requirements.digit_ratio,requirements.special_ratio,requirements.symbol_count.!,requirements.symbol_ratio.!,requirements.symbol_count.?,requirements.symbol_ratio.?,requirements.symbol_count.%,requirements.symbol_ratio.%,requirements.symbol_count.*,requirements.symbol_ratio.*,requirements.symbol_count.&,requirements.symbol_ratio.&,requirements.symbol_count.#,requirements.symbol_ratio.#,requirements.symbol_count..,requirements.symbol_ratio..,requirements.symbol_count.:,requirements.symbol_ratio.:,requirements.symbol_count.,requirements.symbol_ratio.,requirements.symbol_count./,requirements.symbol_ratio./,requirements.symbol_count.;,requirements.symbol_ratio.;,requirements.symbol_count.-,requirements.symbol_ratio.-,benefits.char_count,benefits.word_count,benefits.capital_ratio,benefits.lower_ratio,benefits.digit_ratio,benefits.special_ratio,benefits.symbol_count.!,benefits.symbol_ratio.!,benefits.symbol_count.?,benefits.symbol_ratio.?,benefits.symbol_count.%,benefits.symbol_ratio.%,benefits.symbol_count.$,benefits.symbol_ratio.$,benefits.symbol_count.*,benefits.symbol_ratio.*,benefits.symbol_count.&,benefits.symbol_ratio.&,benefits.symbol_count.#,benefits.symbol_ratio.#,benefits.symbol_count..,benefits.symbol_ratio..,benefits.symbol_count.:,benefits.symbol_ratio.:,benefits.symbol_count.,benefits.symbol_ratio.,benefits.symbol_count./,benefits.symbol_ratio./,benefits.symbol_count.;,benefits.symbol_ratio.;,benefits.symbol_count.-,benefits.symbol_ratio.-,__nlp__.00,__nlp__.000,__nlp__.0in,__nlp__.0in 4pt,__nlp__.0pt,__nlp__.10,__nlp__.10 years,__nlp__.10 years of,__nlp__.100,__nlp__.1000,__nlp__.11,__nlp__.12,__nlp__.12 month,__nlp__.12 months,__nlp__.12 months you,__nlp__.13,__nlp__.14,__nlp__.15,__nlp__.150,__nlp__.1500,__nlp__.1500 job,__nlp__.1500 usd,__nlp__.16,__nlp__.16 18,__nlp__.16 18 year,__nlp__.17,__nlp__.18,__nlp__.18 year,__nlp__.18 years,__nlp__.1871,__nlp__.1st,__nlp__.20,__nlp__.20 years,__nlp__.200,__nlp__.200 cost,__nlp__.2000,__nlp__.2005,__nlp__.2007,__nlp__.2008,__nlp__.2009,__nlp__.2010,__nlp__.2011,__nlp__.2012,__nlp__.2013,__nlp__.2014,__nlp__.2015,__nlp__.21,__nlp__.21st,__nlp__.21st century,__nlp__.24,__nlp__.25,__nlp__.250,__nlp__.28,__nlp__.30,__nlp__.30 countries,__nlp__.30 years,__nlp__.30 years clients,__nlp__.300,__nlp__.35,__nlp__.3d,__nlp__.3d printing,__nlp__.3rd,__nlp__.3rd party,__nlp__.40,__nlp__.40 vacation,__nlp__.400,__nlp__.401,__nlp__.401k,__nlp__.401k plan,__nlp__.401k plan with,__nlp__.45,__nlp__.4pt,__nlp__.50,__nlp__.500,__nlp__.55,__nlp__.60,__nlp__.600,__nlp__.70,__nlp__.75,__nlp__.80,__nlp__.80 vacation,__nlp__.90,...,__nlp__.work and,__nlp__.work as,__nlp__.work as part,__nlp__.work at,__nlp__.work closely,__nlp__.work closely with,__nlp__.work collaboratively,__nlp__.work directly,__nlp__.work effectively,__nlp__.work environment,__nlp__.work ethic,__nlp__.work experience,__nlp__.work experience in,__nlp__.work for,__nlp__.work from,__nlp__.work from home,__nlp__.work hard,__nlp__.work hours,__nlp__.work in,__nlp__.work in an,__nlp__.work in fast,__nlp__.work in the,__nlp__.work independently,__nlp__.work independently and,__nlp__.work is,__nlp__.work life,__nlp__.work life balance,__nlp__.work of,__nlp__.work on,__nlp__.work processes,__nlp__.work that,__nlp__.work to,__nlp__.work together,__nlp__.work together to,__nlp__.work towards,__nlp__.work under,__nlp__.work we,__nlp__.work well,__nlp__.work well with,__nlp__.work will,__nlp__.work will be,__nlp__.work with,__nlp__.work with and,__nlp__.work with our,__nlp__.work with the,__nlp__.work with us,__nlp__.work within,__nlp__.work you,__nlp__.workable,__nlp__.worked,__nlp__.worked in,__nlp__.worked with,__nlp__.worker,__nlp__.workers,__nlp__.workflow,__nlp__.workflows,__nlp__.workforce,__nlp__.workforce solutions,__nlp__.working,__nlp__.working and,__nlp__.working as,__nlp__.working at,__nlp__.working capital,__nlp__.working closely,__nlp__.working closely with,__nlp__.working environment,__nlp__.working experience,__nlp__.working for,__nlp__.working here,__nlp__.working hours,__nlp__.working in,__nlp__.working in an,__nlp__.working in fast,__nlp__.working knowledge,__nlp__.working knowledge of,__nlp__.working on,__nlp__.working relationships,__nlp__.working to,__nlp__.working with,__nlp__.working with the,__nlp__.working within,__nlp__.workload,__nlp__.workplace,__nlp__.works,__nlp__.works with,__nlp__.workshops,__nlp__.world,__nlp__.world and,__nlp__.world and create,__nlp__.world class,__nlp__.world leading,__nlp__.world of,__nlp__.world our,__nlp__.world we,__nlp__.worlds,__nlp__.worldwide,__nlp__.worth,__nlp__.would,__nlp__.would be,__nlp__.would like,__nlp__.would like to,__nlp__.would love,__nlp__.write,__nlp__.write and,__nlp__.writer,__nlp__.writing,__nlp__.writing and,__nlp__.writing skills,__nlp__.written,__nlp__.written and,__nlp__.written and spoken,__nlp__.written and verbal,__nlp__.written communication,__nlp__.written communication skills,__nlp__.written verbal,__nlp__.xml,__nlp__.year,__nlp__.year degree,__nlp__.year experience,__nlp__.year of,__nlp__.year olds,__nlp__.years,__nlp__.years and,__nlp__.years experience,__nlp__.years experience in,__nlp__.years experience with,__nlp__.years in,__nlp__.years of,__nlp__.years of experience,__nlp__.years of professional,__nlp__.years of relevant,__nlp__.years old,__nlp__.years we,__nlp__.years with,__nlp__.yes,__nlp__.yet,__nlp__.york,__nlp__.you,__nlp__.you all,__nlp__.you an,__nlp__.you and,__nlp__.you are,__nlp__.you are interested,__nlp__.you are looking,__nlp__.you are the,__nlp__.you can,__nlp__.you can expect,__nlp__.you could,__nlp__.you do,__nlp__.you do not,__nlp__.you don,__nlp__.you enjoy,__nlp__.you feel,__nlp__.you get,__nlp__.you have,__nlp__.you have experience,__nlp__.you have the,__nlp__.you if,__nlp__.you if you,__nlp__.you in,__nlp__.you know,__nlp__.you like,__nlp__.you like to,__nlp__.you ll,__nlp__.you ll also,__nlp__.you ll be,__nlp__.you ll get,__nlp__.you ll have,__nlp__.you ll need,__nlp__.you ll work,__nlp__.you looking,__nlp__.you love,__nlp__.you may,__nlp__.you may have,__nlp__.you might,__nlp__.you must,__nlp__.you must be,__nlp__.you must have,__nlp__.you need,__nlp__.you need to,__nlp__.you re,__nlp__.you re looking,__nlp__.you should,__nlp__.you should be,__nlp__.you should have,__nlp__.you the,__nlp__.you think,__nlp__.you think you,__nlp__.you to,__nlp__.you to be,__nlp__.you understand,__nlp__.you ve,__nlp__.you ve been,__nlp__.you want,__nlp__.you want to,__nlp__.you we,__nlp__.you we are,__nlp__.you will,__nlp__.you will also,__nlp__.you will be,__nlp__.you will have,__nlp__.you will need,__nlp__.you will work,__nlp__.you with,__nlp__.you work,__nlp__.you would,__nlp__.you would be,__nlp__.you you,__nlp__.young,__nlp__.young and,__nlp__.young people,__nlp__.your,__nlp__.your application,__nlp__.your business,__nlp__.your career,__nlp__.your choice,__nlp__.your cv,__nlp__.your experience,__nlp__.your home,__nlp__.your home we,__nlp__.your job,__nlp__.your knowledge,__nlp__.your new,__nlp__.your own,__nlp__.your project,__nlp__.your responsibilities,__nlp__.your resume,__nlp__.your resume and,__nlp__.your resume to,__nlp__.your role,__nlp__.your skills,__nlp__.your success,__nlp__.your team,__nlp__.your time,__nlp__.your work,__nlp__.yourself,__nlp__.youth,__nlp__.youtube,__nlp__.zero,__nlp__.για,__nlp__.και,__nlp__.με,__nlp__.να,__nlp__.που,__nlp__.σε,__nlp__.την,__nlp__.της,__nlp__.το,__nlp__.του,__nlp__._total_
0,0,0,0,NaN,NaN,0,0,0,NaN,NaN,0,2,3,6,39,14,9,6,1,2,0,9,1,2,1,2,0,0,7,9,0,0,0,0,6,3,9,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,9,1,7,9,0,0,0,0,0,0,0,0,3,6,5,9,3,6,6,7,9,9,5,5,4,8,5,8,2,4,3,3,8,2,0,9,0,0,0,0,0,0,0,0,0,0,0,0,4,9,1,8,3,5,2,8,0,0,8,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,180
1,0,1,1,401,1105,0,0,935,508,697,640,1,0,2,31,0,3,1,5,5,0,0,0,0,0,0,0,0,2,8,0,0,0,0,5,3,3,5,0,4,2,7,1,1,3,2,0,9,0,0,0,0,0,0,0,0,0,0,1,8,0,0,0,0,1,9,1,9,0,0,1,8,0,0,1,0,8,0,9,9,0,0,1,7,0,0,2,7,0,0,0,0,4,8,0,0,2,9,0,0,2,9,0,0,0,0,2,2,9,2,0,7,0,0,0,0,0,0,0,0,0,0,0,0,1,5,0,0,2,4,3,9,0,0,0,0,1,2,6,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,204
2,0,0,0,NaN,754,0,300,908,NaN,NaN,150,2,6,2,58,19,9,7,7,2,0,2,0,0,0,0,0,0,7,8,0,0,0,0,6,3,1,8,0,2,1,0,5,6,4,7,0,4,0,0,0,0,0,0,0,0,0,0,1,5,0,0,3,3,0,0,5,5,0,0,1,4,2,5,8,8,8,2,3,7,0,0,0,0,0,0,0,0,0,0,0,0,1,1,8,5,8,9,8,1,7,8,0,0,5,5,9,9,7,4,4,6,0,0,0,0,0,0,0,0,0,0,1,1,9,5,8,9,9,4,7,7,0,0,5,4,2,2,9,1,0,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,6,0,0,0,0,2,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,299
3,0,1,0,NaN,239,230,0,518,NaN,NaN,NaN,2,1,7,39,20,5,4,9,0,6,5,0,0,0,0,0,0,4,9,0,0,1,7,3,3,7,1,0,5,1,3,5,6,6,7,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,5,0,0,5,5,0,0,0,0,5,9,8,9,2,6,5,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,6,0,0,9,8,0,0,0,0,4,4,7,6,3,9,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,3,3,7,0,0,0,0,4,5,7,4,4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,0,0,5,4,0,0,0,0,1,6,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,1,3,0,0,0,0,0,0,0,0,1,0,0,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,423
4,0,0,0,NaN,230,0,0,0,NaN,NaN,NaN,4,0,0,1,0,5,1,6,2,0,4,0,0,0,0,0,0,1,2,0,0,1,7,1,2,9,0,0,8,1,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,4,6,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,1,7,1,8,0,0,0,0,3,9,7,8,2,5,7,8,0,0,0,0,0,0,0,0,0,0,0,0,2,2,1,2,8,8,2,5,0,0,9,9,2,2,6,1,9,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,9,2,8,0,0,0,0,1,9,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14299,1,0,0,13,NaN,0,0,598,460,0,0,2,6,0,8,6,9,7,9,0,3,1,0,0,0,0,0,0,8,8,0,0,0,0,4,3,3,5,0,4,1,2,2,4,3,9,0,2,0,0,1,8,0,0,0,0,0,0,0,0,0,0,2,8,0,0,3,9,0,0,0,0,0,0,9,9,9,1,6,6,7,5,1,1,9,9,6,4,0,0,0,0,0,0,9,5,2,1,9,9,5,3,2,1,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,1,0,5,0,0,0,0,0,0,0,0,5,1,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,46,0,0,2,3,0,0,0,4,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,3,0,0,0,0,2,1,0,0,9,0,0,0,0,0,3,0,0,0,0,0,0,0,29,0,0,0,1,0,1,0,0,0,0,0,7,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,511
14300,0,1,1,714,92,0,0,913,NaN,0,0,0,0,0,0,0,0,0,1,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,3,1,5,0,7,1,6,3,4,8,2,1,9,1,8,1,8,0,0,0,0,0,0,1,6,1,4,7,9,1,8,3,8,0,0,1,6,0,0,0,1,7,1,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,9,0,0,0,1,1,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,105

In [12]:
predictor.leaderboard(df_test)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.997,0.994,roc_auc,28.919,1159.444,648.788,0.006,0.008,8.083,2,True,7
1,LightGBMXT_BAG_L1,0.996,0.993,roc_auc,6.326,12.454,257.628,6.326,12.454,257.628,1,True,3
2,RandomForestEntr_BAG_L1,0.996,0.993,roc_auc,0.470,596.876,30.492,0.470,596.876,30.492,1,True,6
3,LightGBM_BAG_L1,0.995,0.991,roc_auc,5.864,11.266,287.565,5.864,11.266,287.565,1,True,4
4,RandomForestGini_BAG_L1,0.995,0.992,roc_auc,0.939,287.209,41.792,0.939,287.209,41.792,1,True,5
5,KNeighborsDist_BAG_L1,0.900,0.892,roc_auc,15.313,251.631,23.229,15.313,251.631,23.229,1,True,2
6,KNeighborsUnif_BAG_L1,0.893,0.888,roc_auc,15.655,208.899,16.310,15.655,208.899,16.310,1,True,1

In [16]:
predictor.feature_importance(df_test)

These features in provided data are not utilized by the predictor and will be ignored: ['EVENT_ID']

                     importance  stddev  p_value  n  p99_high  p99_low
company_profile           0.089   0.009    0.000  5     0.108    0.070
description               0.011   0.001    0.000  5     0.013    0.009
requirements              0.002   0.001    0.001  5     0.004    0.001
location                  0.002   0.000    0.000  5     0.003    0.002
benefits                  0.001   0.001    0.003  5     0.003    0.000
has_company_logo          0.001   0.000    0.000  5     0.001    0.001
industry                  0.001   0.000    0.000  5     0.001    0.001
title                     0.001   0.000    0.006  5     0.001   -0.000
required_experience       0.000   0.000    0.044  5     0.000   -0.000
has_questions             0.000   0.000    0.032  5     0.000   -0.000
department                0.000   0.000    0.002  5     0.000    0.000
employment_type           0.000   0.000    0.097  5     0.000   -0.000
telecommuting             0.000   0.000    0.011  5     0.000   -0.000
salary_range             -0.000   0.000    0.826  5     0.000   -0.000
required_education       -0.000   0.000    0.942  5     0.000   -0.000
function                 -0.000   0.000    0.991  5     0.000   -0.000